version: '2'

networks:
  lan:
    #driver: macvlan
    #driver_opts:
    #  parent: enp0s25.87
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.254
  wan:
    driver: bridge

services:
  vcpe:
    build: ./
    cap_add:
     - NET_ADMIN
    hostname: vcpe
    volumes:
     - ./config:/etc/config
    ports:
      - "8080:80"
      - "2222:22"
    networks:
      lan:
        ipv4_address: 192.168.1.1
      wan:

